"""Streaming output through FastAPI.

Article: https://chekh.dev/writing/streaming-output-through-fastapi/
Run:     uv run python streaming_demo.py                 (about fifteen seconds)
         uv run python streaming_demo.py --charts-only   (redraw from results/)

Starts the app from streaming_app.py on a local port, then plays five clients against
it — waiting for the whole answer, streaming, streaming but reading slowly, streaming
and leaving early, waiting for the whole answer and leaving early — and records when
every token was generated by the server and received by the client.
"""

import asyncio
import json
import sys
import threading
import time
from pathlib import Path

import httpx
import matplotlib.pyplot as plt
import uvicorn
from matplotlib.patches import FancyArrowPatch

import streaming_app
from _common import ACCENT, INK, INK_2, MUTED, save

SLUG = "streaming-output-through-fastapi"
PORT = 8765
BASE = f"http://127.0.0.1:{PORT}"
LEAVE_AFTER = 10  # tokens, for the client that leaves early
SLOW_READER = 0.15  # seconds between reads, for the slow client


def start_server() -> None:
    config = uvicorn.Config(streaming_app.app, host="127.0.0.1", port=PORT, log_level="warning")
    threading.Thread(target=uvicorn.Server(config).run, daemon=True).start()
    for _ in range(100):
        try:
            if httpx.get(f"{BASE}/health", timeout=0.2).status_code == 200:
                return
        except httpx.HTTPError:
            time.sleep(0.05)
    raise RuntimeError("the server did not start")


def tokens_in(chunk: str) -> int:
    return sum(1 for line in chunk.split("\n") if line.startswith("data: ") and line != "data: [DONE]")


async def whole_answer(client: httpx.AsyncClient, received: list) -> None:
    response = await client.get(f"{BASE}/answer")
    received.append((len(streaming_app.TOKENS) - 1, time.perf_counter()))
    assert response.json()["answer"].split() == streaming_app.TOKENS


async def streamed(client: httpx.AsyncClient, received: list, pause: float = 0.0, leave_after: int | None = None) -> None:
    count = 0
    async with client.stream("GET", f"{BASE}/stream") as response:
        async for chunk in response.aiter_text():
            for _ in range(tokens_in(chunk)):
                received.append((count, time.perf_counter()))
                count += 1
            if leave_after and count >= leave_after:
                return  # leaving the `with` closes the connection: the server sees a disconnect
            if pause:
                await asyncio.sleep(pause)


async def whole_answer_then_leave(client: httpx.AsyncClient, received: list) -> None:
    try:
        await client.get(f"{BASE}/answer", timeout=0.5)
    except httpx.ReadTimeout:
        pass  # the client gave up; the connection is closed


SCENARIOS = [
    ("whole answer", whole_answer, {}),
    ("streamed", streamed, {}),
    (f"streamed, slow reader", streamed, {"pause": SLOW_READER}),
    (f"streamed, leaves after {LEAVE_AFTER} tokens", streamed, {"leave_after": LEAVE_AFTER}),
    ("whole answer, leaves after 0.5 s", whole_answer_then_leave, {}),
]


async def play() -> dict:
    results: dict = {"tokens": len(streaming_app.TOKENS), "token_seconds": streaming_app.TOKEN_SECONDS, "scenarios": {}}
    async with httpx.AsyncClient(timeout=30) as client:
        for name, fn, kwargs in SCENARIOS:
            streaming_app.events.clear()
            received: list = []
            start = time.perf_counter()
            await fn(client, received, **kwargs)
            await asyncio.sleep(streaming_app.TOKEN_SECONDS * len(streaming_app.TOKENS) + 0.3)  # let the server finish or stop
            generated = [(i, t - start) for kind, i, t in streaming_app.events if kind == "generated"]
            stopped = [i for kind, i, t in streaming_app.events if kind == "stopped"]
            got = [(i, t - start) for i, t in received]
            results["scenarios"][name] = {
                "generated": generated, "received": got,
                "first_token": got[0][1] if got else None,
                "tokens_generated": len(generated), "tokens_received": len(got),
                "server_stopped_after": (stopped[0] + 1) if stopped else None,
            }
            r = results["scenarios"][name]
            first = f"{r['first_token']:.2f} s" if r["first_token"] is not None else "never"
            print(f"{name:36s} first token {first:>7s}   generated {r['tokens_generated']:2d}   received {r['tokens_received']:2d}   "
                  f"server stopped after {r['server_stopped_after']}")
    return results


def draw_timeline(results: dict) -> None:
    names = list(results["scenarios"])
    fig, ax = plt.subplots(figsize=(7.6, 3.8))
    for row, name in enumerate(names):
        s = results["scenarios"][name]
        gen = [t for _, t in s["generated"]]
        got = [t for _, t in s["received"]]
        ax.eventplot(gen, lineoffsets=row - 0.18, linelengths=0.3, colors=[INK_2], linewidths=1)
        if got:
            ax.eventplot(got, lineoffsets=row + 0.18, linelengths=0.3, colors=[ACCENT], linewidths=1.2)
        ax.text(-0.1, row, name, ha="right", va="center", fontsize=8.5, color=INK)
    ax.set_yticks([])
    ax.set_ylim(-0.6, len(names) - 0.4)
    ax.invert_yaxis()
    ax.grid(axis="y", visible=False)
    ax.set_xlim(0, max(t for s in results["scenarios"].values() for _, t in s["generated"] + s["received"]) * 1.04)
    ax.set_xlabel("seconds after the request — grey: generated by the server · green: received by the client")
    ax.set_title("Five clients, one pretend model producing a token every 50 ms", fontsize=10.5)
    fig.subplots_adjust(left=0.34)
    save(fig, SLUG, "timeline")


def draw_sequence() -> None:
    fig, ax = plt.subplots(figsize=(7.6, 3.4))
    ax.set_xlim(0, 7.6)
    ax.set_ylim(0, 3.4)
    ax.axis("off")
    lanes = {"browser": 1.0, "FastAPI": 3.8, "model": 6.6}
    for label, x in lanes.items():
        ax.text(x, 3.15, label, ha="center", va="bottom", fontsize=9.5, color=INK, fontweight="semibold")
        ax.plot([x, x], [0.2, 3.1], color=MUTED, linewidth=1)

    def arrow(x0, x1, y, label, color=INK_2):
        ax.add_patch(FancyArrowPatch((x0, y), (x1, y), arrowstyle="-|>", mutation_scale=9, color=color, linewidth=1))
        ax.text((x0 + x1) / 2, y + 0.07, label, ha="center", va="bottom", fontsize=8, color=color)

    arrow(lanes["browser"], lanes["FastAPI"], 2.8, "GET /stream")
    arrow(lanes["FastAPI"], lanes["model"], 2.55, "generate()")
    for i, y in enumerate([2.2, 1.85, 1.5]):
        arrow(lanes["model"], lanes["FastAPI"], y, f"token {i}")
        arrow(lanes["FastAPI"], lanes["browser"], y - 0.12, f"data: token {i}", color=ACCENT)
    ax.text((lanes["browser"] + lanes["FastAPI"]) / 2, 1.1, "…", ha="center", fontsize=12, color=INK_2)
    arrow(lanes["browser"], lanes["FastAPI"], 0.8, "connection closed")
    arrow(lanes["FastAPI"], lanes["model"], 0.55, "generator closed: stop", color=ACCENT)
    save(fig, SLUG, "sequence")


if __name__ == "__main__":
    path = Path(__file__).parent / "results" / f"{SLUG}.json"
    if "--charts-only" in sys.argv:
        results = json.loads(path.read_text())
    else:
        start_server()
        results = asyncio.run(play())
        path.parent.mkdir(exist_ok=True)
        path.write_text(json.dumps(results))
        print(f"  wrote {path.name}")
    draw_sequence()
    draw_timeline(results)
